#!/bin/bash

echo "Building and installing 3DSTool (x86)..."
#Git Repository
echo "Setting variables..."
gitrepo="https://github.com/dnasdw/3dstool"
gitdir="tmp"

echo "Cleaning..."
#Pre clean up
./clean

echo "Cloning repository..."
#Instructions
git clone --recursive "$gitrepo" "$gitdir"
cd "$gitdir"/cmake
echo "Building..."
cmake -DBUILD64=OFF ..
cmake ..
make
cd ../..
echo "Moving binary to /bin..."
mv "$gitdir"/bin/Release/3dstool /bin/3dstool

echo "Cleaning..."
#Post clean up
rm -rf "$gitdir"
echo "Done!"
