#!/bin/bash

echo "Building 3DSTool..."
#Git Repository
echo "Setting variables..."
gitrepo="https://github.com/dnasdw/3dstool"
gitdir="tmp"

echo "Cleaning..."
#Pre clean up
./clean

echo "Cloning repository..."
#Instructions
git clone --recursive "$gitrepo" "$gitdir"
cd "$gitdir"/cmake
echo "Building..."
cmake -DBUILD64=OFF ..
cmake ..
make
cd ../..
echo "Moving binary to output directory..."
mv "$gitdir"/bin/Release/3dstool out/3dstool_x86

echo "Cleaning..."
#Post clean up
rm -rf "$gitdir"
echo "Done!"
