#!/bin/bash

echo "Building and installing Bannertool..."
#Git Repository
echo "Setting variables..."
gitrepo="https://github.com/steveice10/bannertool"
gitdir="tmp"

echo "Cleaning..."
#Pre clean up
./clean

echo "Cloning repository..."
#Instructions
git clone --recursive "$gitrepo" "$gitdir"
cd "$gitdir"
echo "Building..."
make
cd ../..
echo "Moving binary to /bin..."
mv "$gitdir"/out/bannertool /bin/bannertool

echo "Cleaning..."
#Post clean up
rm -rf "$gitdir"
echo "Done!"
