#!/bin/bash

echo "Building and installing citro3d..."
#Git Repository
echo "Setting variables..."
gitrepo="https://github.com/fincs/citro3d.git"
gitdir="tmp"


echo "Cleaning"
#Pre clean up
./clean

echo "Cloning repository..."
#Instructions
git clone --recursive "$gitrepo" "$gitdir"
cd "$gitdir"/libctru
echo "Building and installing..."
make install
cd ../..

echo "Cleaning..."
#Post clean up
rm -rf "$gitdir"
echo "Done!"
