#!/bin/bash

#Additional Requirements for Build
#
# * libtool
# * automake
#
#

echo "Building Corbenik CFW..."
#Git Repository
echo "Setting variables..."
gitrepo="https://github.com/chaoskagami/corbenik"
gitdir="tmp"

echo "Cleaning..."
#Pre clean up
./clean

echo "Cloning repository..."
#Instructions
git clone --recursive "$gitrepo" "$gitdir"
cd "$gitdir"
echo "Building..."
./autogen.sh
./configure --host=arm-none-eabi
make
cd ..
echo "Moving files to output directory..."
mv "$gitdir"/out out

echo "Cleaning..."
#Post clean up
rm -rf "$gitdir"
echo "Done!"
