#!/bin/bash

echo "Building CTRTool..."
#Git Repository
echo "Setting variables..."
gitrepo="https://github.com/profi200/Project_CTR"
gitdir="tmp"

echo "Cleaning..."
#Pre clean up
./clean

echo "Cloning repository..."
#Instructions
git clone --recursive "$gitrepo" "$gitdir"
cd "$gitdir"/ctrtool
echo "Building..."
make
cd ../..
mkdir out
echo "Moving files to output directory..."
mv "$gitdir"/ctrtool/ctrtool out/ctrtool

echo "Cleaning..."
#Post clean up
rm -rf "$gitdir"
echo "Done!"
