#!/bin/bash

echo "Building Decrypt9UI..."
#Git Repository
echo "Setting variables..."
gitrepo="https://github.com/Shadowtrance/Decrypt9"
gitdir="tmp"

echo "Cleaning..."
#Pre clean up
./clean

echo "Cloning repository..."
#Instructions
git clone --recursive "$gitrepo" "$gitdir"
cd "$gitdir"
echo "Building..."
make
cd ..
echo "Moving files to output directory..."
mv "$gitdir"/output out

echo "Cleaning..."
#Post clean up
rm -rf "$gitdir"
echo "Done!"
