#!/bin/bash


#Git Repository
gitrepo="https://github.com/d0k3/Hourglass9"
gitdir="tmp"


#Pre clean up
rm -rf out
rm -rf "$gitdir"

#Instructions
git clone --recursive "$gitrepo" "$gitdir"
cd "$gitdir"
make
cd ..
mv "$gitdir"/output out

#Post clean up
rm -rf "$gitdir"
