#!/bin/bash


#Git Repository
gitrepo="https://github.com/billy-acuna/LimaCFW"
gitdir="tmp"


#Pre clean up
./clean

#Instructions
git clone --recursive "$gitrepo" "$gitdir"
cd "$gitdir"
make
cd ..
mv "$gitdir"/out out

#Post clean up
rm -rf "$gitdir"
