#!/bin/bash

echo "Building Luma3DS..."
#Git Repository
echo "Setting variables..."
gitrepo="https://github.com/AuroraWright/Luma3DS"
gitdir="tmp"

echo "Cleaning..."
#Pre clean up
./clean

echo "Cloning repository..."
#Instructions
git clone --recursive "$gitrepo" "$gitdir"
cd "$gitdir"
echo "Building..."
make
cd ..
echo "Moving files to output directory..."
mv "$gitdir"/out out

echo "Cleaning..."
#Post clean up
rm -rf "$gitdir"
echo "Done!"
