#!/bin/bash

echo "Building and installing MakeROM..."
#Git Repository
echo "Setting variables..."
gitrepo="https://github.com/profi200/Project_CTR"
gitdir="tmp"

echo "Cleaning..."
#Pre clean up
./clean

echo "Cloning repository..."
#Instructions
git clone --recursive "$gitrepo" "$gitdir"
cd "$gitdir"/makerom
echo "Building..."
make
cd ../..
mkdir out
echo "Moving file to /bin ..."
mv "$gitdir"/makerom/makerom /bin/makerom

echo "Cleaning..."
#Post clean up
rm -rf "$gitdir"
echo "Done!"
