#!/bin/bash


#Git Repository
gitrepo="https://github.com/profi200/Project_CTR"
gitdir="tmp"


#Pre clean up
./clean

#Instructions
git clone --recursive "$gitrepo" "$gitdir"
cd "$gitdir"/makerom
make
cd ../..
mkdir out
mv "$gitdir"/makerom/makerom out/makerom

#Post clean up
rm -rf "$gitdir"
