#!/bin/bash

echo "Building Puma33DS..."
#Git Repository
echo "Setting variables..."
gitrepo="https://github.com/rboninsegna/Puma33DS.git"
gitdir="tmp"

echo "Cleaning..."
#Pre clean up
./clean

echo "Cloning repository..."
#Instructions
git clone --recursive "$gitrepo" "$gitdir"
cd "$gitdir"
echo "Building..."
make
cd ..
echo "Moving files to output directory..."
mv "$gitdir"/out out

#Post clean up
echo "Cleaning..."
rm -rf "$gitdir"
echo "Done!"
