#!/bin/bash

echo "Building ReiNand+..."
#Git Repository
echo "Setting variables..."
gitrepo="https://github.com/Hikiruka/ReiNand-Plus.git"
gitdir="tmp"

echo "Cleaning..."
#Pre clean up
./clean

echo "Cloning repository..."
#Instructions
git clone --recursive "$gitrepo" "$gitdir"
cd "$gitdir"
echo "Building..."
make a9lh
cd ..
echo "Moving files to output directory..."
mv "$gitdir"/out out

echo "Cleaning..."
#Post clean up
rm -rf "$gitdir"
echo "Done!"
